from enum import Enum


class JwtCause(Enum):
    """JWT loader response causes."""

    ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_FAILED = "TOKEN_FAILED"
    NEEDS_FRESH_TOKEN = "NEEDS_FRESH_TOKEN"
    MISSING_TOKEN = "MISSING_TOKEN"
    REVOKED_TOKEN = "REVOKED_TOKEN"
